### ISSUE TITLE
Example Flow Please:-)

### ISSUE THREAD

**Issue by thejollypop** [iceglow/node-red-contrib-deepstack#1]
Hello iceglow:)

Looks great, but I couldn't make it work... I keep getting:

`"Credential type 'deepstack-face-recognition' is not registered"`

and also:

`"Error: 'input' must not start with a slash when using 'prefixUrl'"`
 
I don't really know what to do next end where is the right place to paste my API KEY. 
An example flow will be highly appreciated! Thanks

**Comment by kgalilio** [comment]
> Hello iceglow:)
> 
> Looks great, but I couldn't make it work... I keep getting:
> 
> `"Credential type 'deepstack-face-recognition' is not registered"`
> 
> and also:
> 
> `"Error: 'input' must not start with a slash when using 'prefixUrl'"`
> 
> I don't really know what to do next end where is the right place to paste my API KEY.
> An example flow will be highly appreciated! Thanks

I am facing the same issue.
Any solution to the problem?

**Comment by ministryofsillywalks** [comment]
Same for me. Would love to hear from the dev how to set this up correctly.

**Comment by iceglow** [comment]
Hi guys,
First of all, sorry. for the slow response!

I've provided a simple sample for the object detection, I'll add one for the face detection asap.

**Comment by iceglow** [comment]
> I don't really know what to do next end where is the right place to paste my API KEY.

In regards of the API KEY, I've not yet added support for that. If that's a feature people are waiting for, I'll make sure to prioritize adding it.
