### ISSUE TITLE
Great Project!!!

### ISSUE THREAD

**Issue by OlafenwaMoses** [iceglow/node-red-contrib-deepstack#13]
Hi @iceglow , I am Moses Olafenwa, the CEO of the company building and maintaining DeepStack AI Server.

This is a very wonderful project you have here, developing a nice, seamless integration for DeepStack on the Node-RED platform.  My team will publish a tutorial soon on this project on our Blog and will feature it on our developer sites too.

**Comment by iceglow** [comment]
Hi @OlafenwaMoses,
Deepstack and NodeRED are some of my absolute favourite software, so this news makes me very happy.
Don't hesitate to reach out with feature requests, and as always, code contributions are more than welcome.

**Comment by OlafenwaMoses** [comment]
@iceglow Thanks for the kind response. We surely will be happy to contribute to this project going forward.

As promised, here is the tutorial our team published on DeepStack, Node-RED and the Node-RED-Contrib-DeepStack. Check it out and share with your network.

https://medium.com/deepquestai/no-code-ai-automation-with-deepstack-and-node-red-c8ed40fbbe62

**Comment by OlafenwaMoses** [comment]
BTW: The above article is one out of many we will publish on Node-RED-Contrib-DeepStack
