### ISSUE TITLE
sharp library is killing the node-red process

### ISSUE THREAD

**Issue by danielo515** [iceglow/node-red-contrib-deepstack#3]
Hello
I tried using this module with my own flow and the provided example ones and all I get is an idling status, no error, no output.
My deepstack server is working because I can get appropriate responses using an http request.

**Comment by danielo515** [comment]
Ok I found the problem.
The sharp library is triggering a core dump (probably because a memory leak) when It tries to read the image in any way, killing the node process, triggering a restart node-red and making impossible any kind of error handling, because the entire node process dies.
As a workaround, if you just not use the write shapes on the image the integration works fine. Please consider switching to a more reliable library, this never happened to me before, and I used several image processing libraries

**Comment by iceglow** [comment]
That's unfortunate. What kind of images are you working with?
Maybe you can file a bug report to the [Sharp](https://github.com/lovell/sharp) project to get them to look into it, I'm sure they'll appreciate it?

**Comment by danielo515** [comment]
> What kind of images are you working with?

Normal security camera images. They are 2.048 x 1.536‬ in size, but just a couple of kilobytes in weight. The sharp library seems to have a lot of stupid issues about this, and I am not sure I'm going to contribute with just another problem to their list, but I'll try

**Comment by iceglow** [comment]
Too bad, I've always liked libvips.

**Comment by lovell** [comment]
This issue has been reported against sharp at https://github.com/lovell/sharp/issues/2595 and it looks like a conflict between two different versions of sharp.

If possible, please can you upgrade the version of sharp used by this package to v0.28.0 as it provides statically-built binaries to help avoid this entire class of problem. Thank you!

**Comment by danielo515** [comment]
I can confirm that the problem is not conflicting versions, because this was happening before I installed a different version of sharp to reproduce this problem and it persist after I removed it.
I will, however, try with sharp 0.28.0

**Comment by danielo515** [comment]
Tried with 0.28.0 and still fails:

![image](https://user-images.githubusercontent.com/2270425/112953188-91cb8980-913d-11eb-8a27-6cedc443d98f.png)

Repro:
```js
outlines = [{x: 0, y: 10, height: 50, width: 50}]
image = '/config/www/cam_captures/kitchen.jpg'
buffer = fs.readFileSync(image)
sharp = require('node-red-contrib-deepstack/node_modules/sharp')

const outline = function(buffer, outlines, outlineColor) {
        return sharp(buffer).metadata().then(meta => {
              let svgOverlay = '';

            outlines.forEach(o => {
                svgOverlay += '<rect x="' + o.x + '" y="' + o.y + '" width="' + o.width + '" height="' + o.height + '" ' +
                    'style="fill:none;stroke:' + outlineColor + ';stroke-width:3;" />';
            });
            return '<svg width="' + meta.width + '" height="' + meta.height + '">' + svgOverlay + '</svg>';
        }).then(overlay => {
            return sharp(buffer).composite([{
                input: Buffer.from(overlay),
                blend: 'over'
            }]).toBuffer();
        });
    }

outline(buffer, outlines, '#fff')

```

**Comment by danielo515** [comment]
Oh, stupid me, I installed latest sharp but I was still requiring the one from the library.

I just updated the library sharp version (but going into the npm folder and updating it) and I can confirm that the above code no longer fails and produces the desired image with a white rectangle at the desired coords

**Comment by iceglow** [comment]
456cedd should do it.
Huge thanks @danielo515 for all the help & @lovell for an amazing module!
