### ISSUE TITLE
Face Registration

### ISSUE THREAD

**Issue by bdydrp** [iceglow/node-red-contrib-deepstack#5]
Any chance you can add a node for Face registration?

**Comment by iceglow** [comment]
Getting started on it.. you can check it out in https://github.com/iceglow/node-red-contrib-deepstack/tree/face_reg

**Comment by bdydrp** [comment]
Awesome. Thanks.
I will try this out
Cheers

**Comment by iceglow** [comment]
v0.1.0 should do it for you. https://flows.nodered.org/node/node-red-contrib-deepstack
