### ISSUE TITLE
Custom Models

### ISSUE THREAD

**Issue by deepc2020** [iceglow/node-red-contrib-deepstack#9]
It would be really cool to be able to select a custom model in the UI.

**Comment by iceglow** [comment]
Hi @deepc2020,
Looked into your implementation of custom models in your fork. Would you be ok with submitting a pull request back to this project, and I'll happily merge it.

**Comment by hillbicks** [comment]
It would be great if we could have the option to change the custom model. I'm implementing the openlogo model for deepstack and it would prefer to use this node.

Thanks for your work on this!

**Comment by iceglow** [comment]
Getting started on it in [this branch](/iceglow/node-red-contrib-deepstack/tree/issue-09). Thanks to @deepc2020, for his contribution!

**Comment by iceglow** [comment]
v0.2.1 should have a new node for using custom models.
